# Generated by Django 5.2 on 2025-04-19 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_atendimento', models.CharField(max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('compareceu', 'Compareceu'), ('nao_compareceu', 'Não Compareceu'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_tecnicos', to=settings.AUTH_USER_MODEL)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='DemandaEspontanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(max_length=50)),
                ('motivo_procura', models.TextField()),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('data_registro', models.DateTimeField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficiario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(max_length=50)),
                ('origem', models.CharField(choices=[('agendamento', 'Agendamento'), ('demanda_espontanea', 'Demanda Espontânea'), ('encaminhamento', 'Encaminhamento')], max_length=20)),
                ('data_atendimento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('evolucao', models.TextField(blank=True, null=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to=settings.AUTH_USER_MODEL)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficiario')),
                ('demanda_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.demandaespontanea')),
            ],
        ),
    ]
