# Generated by Django 5.2 on 2025-04-19 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('populacao', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nome_mae',
            field=models.CharField(default='Não informado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(default='Não informado', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CRAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('coordenador', models.CharField(max_length=100)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade')),
            ],
            options={
                'verbose_name': 'CRAS',
                'verbose_name_plural': 'CRAS',
            },
        ),
        migrations.CreateModel(
            name='AtividadeSCFV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('faixa_etaria', models.CharField(max_length=50)),
                ('frequencia_esperada', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('cras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cras')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cras'),
        ),
        migrations.CreateModel(
            name='FichaPAIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paif', models.CharField(help_text='Número único da família no PAIF', max_length=50, unique=True)),
                ('data_cadastro', models.DateField()),
                ('responsavel_familiar', models.CharField(max_length=100)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('nis_responsavel', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo_moradia', models.CharField(max_length=50)),
                ('tipo_construcao', models.CharField(max_length=50)),
                ('energia_eletrica', models.CharField(max_length=50)),
                ('inst_sanitaria', models.CharField(max_length=50)),
                ('agua', models.CharField(max_length=50)),
                ('lixo', models.CharField(max_length=50)),
                ('local_de_risco', models.BooleanField(default=False)),
                ('numero_comodos', models.IntegerField()),
                ('numero_quartos', models.IntegerField()),
                ('receita_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantos_trabalham', models.IntegerField()),
                ('beneficios', models.CharField(blank=True, max_length=255)),
                ('despesas_fixas', models.TextField(blank=True)),
                ('demanda_origem', models.CharField(max_length=100)),
                ('confidencial', models.BooleanField(default=False)),
                ('cras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cras')),
            ],
            options={
                'verbose_name': 'Ficha PAIF',
                'verbose_name_plural': 'Fichas PAIF',
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='ficha_paif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fichapaif'),
        ),
        migrations.CreateModel(
            name='FichaSCFV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('situacao_escolar', models.CharField(max_length=100)),
                ('publico_prioritario', models.CharField(max_length=255)),
                ('beneficio_social', models.CharField(blank=True, max_length=100, null=True)),
                ('pressao_alta', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('outros_saude', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficiario')),
            ],
            options={
                'verbose_name': 'Ficha SCFV',
                'verbose_name_plural': 'Fichas SCFV',
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoSCFV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_participacao', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('avaliacao', models.TextField(blank=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividadescfv')),
                ('ficha_scfv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fichascfv')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('desenvolvedor', 'Desenvolvedor'), ('coordenador', 'Coordenador'), ('assistente_social', 'Assistente Social'), ('tecnico_pedagogico', 'Técnico Pedagógico'), ('orientador', 'Orientador'), ('recepcionista', 'Recepcionista')], max_length=50)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cras')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
