# Generated by Django 5.2 on 2025-04-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cidade_beneficiario_endereco_beneficiario_nis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichapaif',
            old_name='cpf_responsavel',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='fichapaif',
            old_name='data_cadastro',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='fichapaif',
            old_name='confidencial',
            new_name='demanda_buscativa',
        ),
        migrations.RenameField(
            model_name='fichapaif',
            old_name='local_de_risco',
            new_name='demanda_encaminada',
        ),
        migrations.RenameField(
            model_name='fichapaif',
            old_name='nis_responsavel',
            new_name='despesa_agua',
        ),
        migrations.RenameField(
            model_name='fichapaif',
            old_name='demanda_origem',
            new_name='municipio',
        ),
        migrations.RenameField(
            model_name='fichapaif',
            old_name='responsavel_familiar',
            new_name='nome_referencia',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='despesas_fixas',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='inst_sanitaria',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='lixo',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='numero_comodos',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='numero_quartos',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='quantos_trabalham',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='receita_mensal',
        ),
        migrations.RemoveField(
            model_name='fichapaif',
            name='tipo_moradia',
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='abastecimento_agua',
            field=models.CharField(blank=True, choices=[('rede_publica', 'Rede Pública Encanada'), ('carro_pipa', 'Carro Pipa / Poço'), ('correntes_naturais', 'Correntes de Água Natural'), ('torneira_coletiva', 'Torneiras Coletivas'), ('outro', 'Outro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='demanda_espontane',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='demanda_outros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='despesa_alimentacao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='despesa_aluguel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='despesa_gas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='despesa_luz',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='despesa_transporte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='destino_esgoto',
            field=models.CharField(blank=True, choices=[('ceu_aberto', 'Céu Aberto'), ('fossa', 'Fossa'), ('outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='destino_lixo',
            field=models.CharField(blank=True, choices=[('coleta_domiciliar', 'Coleta Domiciliar'), ('queimado', 'Queimado'), ('cacamba', 'Caçamba'), ('enterrado', 'Enterrado'), ('outro', 'Outro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='energia_eletrica_outros',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='instalacao_sanitaria',
            field=models.CharField(blank=True, choices=[('fossa_septica', 'Fossa Séptica'), ('fossa_rudimentar', 'Fossa Rudimentar')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='local_risco',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='moradia',
            field=models.CharField(blank=True, choices=[('propria', 'Própria'), ('alugada', 'Alugada'), ('financiada', 'Financiada'), ('cedida', 'Cedida'), ('ocupacao', 'Ocupação'), ('outra', 'Outra')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='moradia_outra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='nis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='num_comodos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='num_integrantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='num_quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='num_trabalham',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='raca',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('parda', 'Parda'), ('negra', 'Negra'), ('quilombola', 'Quilombola'), ('indigena', 'Indígena'), ('outra', 'Outra')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='renda_total',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='tipo',
            field=models.CharField(choices=[('inclusao', 'Inclusão'), ('atualizacao', 'Atualização')], default='inclusao', max_length=20),
        ),
        migrations.AddField(
            model_name='fichapaif',
            name='tipo_construcao_outros',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaif',
            name='beneficios',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaif',
            name='energia_eletrica',
            field=models.CharField(blank=True, choices=[('relogio', 'Relógio'), ('improvisado', 'Improvisado'), ('outros', 'Outros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaif',
            name='tipo_construcao',
            field=models.CharField(blank=True, choices=[('tijolo', 'Tijolo/Alvenaria'), ('taipa_revestida', 'Taipa Revestida'), ('taipa_nao_revestida', 'Taipa Não Revestida'), ('madeira', 'Madeira'), ('madeira_reaproveitada', 'Madeira Reaproveitada'), ('outros', 'Outros')], max_length=30, null=True),
        ),
    ]
