# Generated by Django 5.2 on 2025-04-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cpf_responsavel_fichapaif_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
